gemini:
  api:
    key: ${GEMINI_API_KEY}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
     url: jdbc:mariadb://${DB_url}:${DB_port}/blog
     username: ${DB_username}
     password: ${DB_password}
     driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  jackson:
    serialization:
      indent_output: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  file:
    upload-dir: /app/uploads
